// AUTO-GENERATED: do not edit by hand.
//
// This file is regenerated by `script/build.ts` after each Vite build with
// the contents of `dist/public/index.html`. The catch-all Pages Function
// imports `HTML_SHELL` and uses it as the base shell into which per-route
// SEO/meta/JSON-LD/body content is injected.
//
// The empty placeholder below is the committed default so TypeScript can
// compile in a fresh checkout. At runtime, the catch-all detects the empty
// shell and falls back to `env.ASSETS.fetch('/index.html')` until the
// build step replaces this file.
export const HTML_SHELL: string = "";
