import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { cp, rm, readFile, writeFile, stat } from "fs/promises";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "@neondatabase/serverless",
  "axios",
  "connect-pg-simple",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  console.log("copying public/ assets (product images, etc.) into dist/public/...");
  try {
    await stat("public");
    await cp("public", "dist/public", { recursive: true, force: false, errorOnExist: false });
  } catch (e: any) {
    if (e?.code !== "ENOENT") throw e;
  }

  // NOTE: attached_assets/ is intentionally NOT copied into dist/public.
  // The directory holds raw uploads (including multi-MB zips) that exceed
  // Cloudflare Pages' 25 MiB per-file limit. The DB has been cleaned so no
  // product references /attached_assets/* URLs anymore. Anything that still
  // needs to be web-served lives under public/ or is mirrored below.

  // Mirror attached_assets/stock_images at /stock_images so URLs that use the
  // dev-only Express alias (`app.use('/stock_images', ...)`) keep working in
  // production on Cloudflare Pages (categories, etc.).
  console.log("copying attached_assets/stock_images/ into dist/public/stock_images/...");
  try {
    await stat("attached_assets/stock_images");
    await cp("attached_assets/stock_images", "dist/public/stock_images", { recursive: true, force: false, errorOnExist: false });
  } catch (e: any) {
    if (e?.code !== "ENOENT") throw e;
  }

  // Embed the built index.html shell into a TypeScript module so the
  // Cloudflare Pages catch-all function can use it as a constant. This
  // avoids a per-request `env.ASSETS.fetch('/index.html')` round trip and
  // guarantees the shell version always matches the deployed bundle.
  console.log("embedding html shell into functions/_lib/html-shell.generated.ts...");
  const shellHtml = await readFile("dist/public/index.html", "utf-8");
  const shellModule =
    `// AUTO-GENERATED by script/build.ts — do not edit.\n` +
    `// Regenerated from dist/public/index.html on every build.\n` +
    `export const HTML_SHELL = ${JSON.stringify(shellHtml)};\n`;
  await writeFile("functions/_lib/html-shell.generated.ts", shellModule, "utf-8");

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    outfile: "dist/index.cjs",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
