import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, writeFile } from "fs/promises";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "@neondatabase/serverless",
  "axios",
  "connect-pg-simple",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  // Embed the built index.html shell into a TypeScript module so the
  // Cloudflare Pages catch-all function can use it as a constant. This
  // avoids a per-request `env.ASSETS.fetch('/index.html')` round trip and
  // guarantees the shell version always matches the deployed bundle.
  console.log("embedding html shell into functions/_lib/html-shell.generated.ts...");
  const shellHtml = await readFile("dist/public/index.html", "utf-8");
  const shellModule =
    `// AUTO-GENERATED by script/build.ts — do not edit.\n` +
    `// Regenerated from dist/public/index.html on every build.\n` +
    `export const HTML_SHELL = ${JSON.stringify(shellHtml)};\n`;
  await writeFile("functions/_lib/html-shell.generated.ts", shellModule, "utf-8");

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    outfile: "dist/index.cjs",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
